services:
  redis:
    image: redis:7-alpine
    container_name: smartretail-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    restart: unless-stopped

volumes:
  redis-data: