services:
  redis:
    image: redis:7-alpine
    container_name: smartretail-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    env_file:
      - .env.dev
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
      - /Users/jinyuanzhang/IdeaProjects/smartretail360/data/logs:/var/log/smartretail360
    ports:
      - "4317:4317"  # gRPC
      - "4318:4318"  # HTTP

volumes:
  redis-data: