packages:
  - 'apps/*'
  - 'packages/*'
  - 'libs/*'
  - 'ci'
  - 'scripts'


# Declares which subprojects belong to the monorepo.
# Each subproject (e.g., apps/client, apps/ai-services) only declares its dependencies in its own package.json.
# When you run `pnpm install` from the root:
#    • All dependencies are downloaded into the .pnpm/ directory (deduplicated and globally cached)
#    • Hard links are created into the top-level node_modules directory
#    • Each subproject no longer has its own node_modules — dependencies are resolved via the shared .pnpm/ store