migrate-update:
  dotnet ef database update \
    --project ./SmartRetail360.Infrastructure/SmartRetail360.Infrastructure.csproj \
    --startup-project ./SmartRetail360.API/SmartRetail360.API.csproj \
    --context AppDbContext
    
migrate-add name:
  dotnet ef migrations add {{name}} \
    --project ./SmartRetail360.Infrastructure/SmartRetail360.Infrastructure.csproj \
    --startup-project ./SmartRetail360.API/SmartRetail360.API.csproj \
    --output-dir Data/Migrations \
    --context AppDbContext    
    
migrate-clean:
  rm -rf SmartRetail360.Infrastructure/Data/Migrations/*