namespace SmartRetail360.Shared.Enums;

public enum LogEventType
{
    RegisterUserSuccess,
    RegisterUserFailure,
    InviteUserSuccess,
    InviteUserFailure,
    CredentialsLoginFailure,
    LoginSuccess,
    LoginFailure,
    OAuthLoginFailure,
    AccountActivateSuccess,
    AccountActivateFailure,
    EmailSendSuccess,
    EmailSendFailure,
    WriteLogFailure,
    RedisError,
    SqsError,
    RefreshTokenFailure,
    DatabaseError,
    LogoutFailed,
    ConfirmTenantLoginFailure,
    ConfirmTenantLoginSuccess,
    RefreshTokenReplayDetected,
    AuthorizationFailure,
    UpdateAbacPolicyFailure,
    UpdateAbacPolicySuccess,
    TokenValidationFailure,
    AbacPolicyEvaluationFailure,
    GetAbacResolverFailure,
    GetAbacResourceFailure,
    GetAbacPoliciesSuccess,
    UpdateUserBasicProfileSuccess,
    UpdateUserBasicProfileFailure,
}